
///.This Javscript code is designed to create a webpage where the background color chnages randomly when a `start` button is clicked and stops changing when a `stop` button is clicked.

///1.Generate a random color:-
 //The `randomColor` function generates a random color in hexadecimal format(like #FF5733)
 //-using a combination of numbers(0-9) and letters (A-F).

const randomColor = function() {
    const hex = '0123456789ABCDEF';
    let color = '#'
    for (let i = 0; i < 6; i++) {
        color += hex[Math.floor(Math.random() * 16)];
    }
    return color;
};

///2.Declared a variable `intervalId` and  Added to the global scope.
let intervalId; 


///3.Starting and stoping color change:-
 //There are two functions startChangingColor and stopChangingColor.

const startChangingColor = function() {
    function changeBgColor() {
        document.body.style.backgroundColor = randomColor();
    }

    intervalId = setInterval(changeBgColor, 1000);
};
//`startChangingColor` When called, it starts changing the background color.
//It uses `setInterval` to repeatedly call a function called`changeBgColor` evvery 1000 miliseconds = 1 second.
//`changeBgcolor` sets the background color of the webpages body to a random color generated by `randomColor`.
document.querySelector("#start").addEventListener('click', startChangingColor); // Corrected ID

//`stopChangingColor` when called, it stops the color changing process.
//It uses ` clearInterval` to stop the interval that was set by `setInterval`
const stopChangingColor = function() {
    clearInterval(intervalId);
};


///.Button event listeners:-
//There are two buttons in the html with IDs "start" and "stop".
//The code sets up event listener so that when the `start` button is clicked, it calls`startChangingColor`
//And when the `stop` button is clicked, it calls `stopChangingColor`.

document.querySelector("#stop").addEventListener('click', stopChangingColor); // Corrected ID




//1.
 //Hexvalues are total 16, Hexadecimal is a base-16 number system that uses a set of 16.

 //The 16 didgits of the hexadecimal are:-
 //1,2,3,4,5,6,7,8,9,A,B,C,D,E,F.

//2.`#` is know for Hex values.

//3.`Math.Floor()`:-
 //Math.floor is an inbuilt function in javscript that returns a largest integer is less than or equal to a given number.


//4.`Math.Random()`:-
 //Math.Random is an inbult function in javascript that generates a random floating number between 0(inclusive) and 1(exclusive) it doesnot take any arguments.
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

///.For practice:-

// const randomColors = function()
// {

// const hexValues = "0123456789ABCDEF";
// let color = "#";
// for(let i = 0; i < 6; i++)
// {
//     color += hexValues[Math.floor(Math.random() *  16)];
// }
// return color;
// };

// let intervalId;
// const startChangingColor = function()
// {
//     function changeBgColor()
//     {
        
//         document.body.style.backgroundColor = randomColors();
//     }
//     intervalId = setInterval(changeBgColor,1000);
// };

// document.querySelector("#start").addEventListener('click',startChangingColor);

// const stopChangingColor = function()
// {
// clearInterval(intervalId);


// };
// document.querySelector("#stop").addEventListener('click',stopChangingColor);